# Generated by Django 3.2.13 on 2023-04-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marketsample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batterytype', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=9)),
                ('description', models.CharField(max_length=99)),
                ('mfg', models.CharField(max_length=9)),
                ('price', models.IntegerField()),
                ('shelflife', models.CharField(max_length=9)),
                ('receivedate', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trialdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setno', models.CharField(max_length=5)),
                ('trialdate', models.DateField(auto_now_add=True, null=True)),
                ('batterytype', models.CharField(max_length=9)),
                ('trial_location', models.CharField(max_length=9)),
                ('description', models.CharField(max_length=25)),
                ('receivedate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
