# Generated by Django 3.2.13 on 2023-04-23 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='market_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Mfg', models.CharField(max_length=50)),
                ('market_img', models.ImageField(upload_to='static/')),
                ('receivedate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
