# Generated by Django 3.2.13 on 2023-04-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_market_img_market_image_market_sample_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_no', models.CharField(max_length=5)),
                ('complainer', models.CharField(max_length=25)),
                ('battery_type', models.CharField(max_length=9)),
                ('description', models.CharField(max_length=99)),
                ('mfg', models.CharField(max_length=9)),
                ('status', models.CharField(max_length=99)),
                ('receivedate', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
