# Generated by Django 3.2.13 on 2023-05-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='testsample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivedno', models.CharField(max_length=5)),
                ('samplename', models.CharField(max_length=99)),
                ('description', models.CharField(max_length=99)),
                ('mfg', models.CharField(max_length=9)),
                ('teststatus', models.CharField(max_length=20)),
                ('receivedate', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
