# Generated by Django 3.2.13 on 2023-05-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_test_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(max_length=5)),
                ('date', models.CharField(max_length=9)),
                ('suppliername', models.CharField(max_length=99)),
                ('amount', models.CharField(max_length=9)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
